name: 'List Open Pull Request Titles'
description: 'List open pull requests for a given repository'
icon: git-pull-request
color: green
inputs:
  token:
    description: 'gh token'
    required: true
    default: ''
  owner:
    description: 'repo owner'
    required: true
    default: 'jkisk'
  repo:
    description: 'repo'
    required: true
    default: 'list-open-pulls'
outputs:
  titles:
    description: 'list of open pr titles'
runs:
  using: 'node16'
  main: 'dist/index.js'